export * from "./auth.api";
export * from "./course.api";
export * from "./department.api";
export * from "./institution.api";
export * from "./payment.api";
export * from "./student.api";
export * from "./super_admin.api";
export * from "./teacher.api";
export * from "./user.api";
